# -*- coding: utf-8 -*-
"""Trashify - Capstone Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iBUdFjgT5xXboQW5bdXRMQoV9CL43eab

# **Proyek Capstone: Trashify - Data Preparation & Analysis**

Notebook ini disusun untuk mendokumentasikan proses pengolahan data gambar secara untuk klasifikasi sampah. Proses ini meliputi tahap Data Wrangling (Gathering, Assessing, Cleaning) hingga Exploratory Data Analysis (EDA) guna memastikan dataset siap digunakan oleh tim Artificial Intelligence.

## Menentukan Pertanyaan Bisnis
Sebelum melakukan *Data Wrangling* dan eksplorasi, berikut adalah pertanyaan yang akan dijawab melalui proses analisis ini untuk memastikan kualitas model AI Trashify:

1. **Pertanyaan 1:** Sejauh mana tingkat ketidakseimbangan kelas pada dataset mentah, dan bagaimana kita memastikan komposisi data seimbang agar model AI terhindar dari bias?
2. **Pertanyaan 2:** Bagaimana distribusi ukuran resolusi dan format warna pada dataset mentah, dan apakah langkah standarisasi visual diperlukan sebelum data diekspor?
3. **Pertanyaan 3:** Berapa banyak file citra dalam dataset mentah yang terindikasi rusak (*corrupt*) atau memiliki format warna tidak standar, yang harus dibersihkan?

# Import Library/Packages yang Digunakan
"""

!pip install split-folders

# Commented out IPython magic to ensure Python compatibility.
import os
import shutil
import random
import kagglehub
import splitfolders
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from PIL import Image

# %matplotlib inline

"""# 1. Data Wrangling
Tahap ini bertujuan untuk mengumpulkan data mentah, menilai kualitasnya, dan membersihkannya dari anomali sebelum masuk ke tahap analisis.

###1.1 Data Gathering
Pada tahap ini, kita akan mengumpulkan dataset yang relevan dari repositori publik (*Kaggle*). Data yang masih bersifat *read-only* akan disalin ke dalam `working directory` agar dapat dimodifikasi pada tahapan selanjutnya.
"""

# Mengunduh dataset
raw_path = kagglehub.dataset_download("zillyz/sampah-organik-anorganik-residu")

# Penyesuaian struktur direktori
contents = os.listdir(raw_path)
base_source = os.path.join(raw_path, contents[0]) if len(contents) == 1 else raw_path

# Menyiapkan direktori kerja
working_dir = "/content/Trashify_Dataset"
if os.path.exists(working_dir):
    shutil.rmtree(working_dir)

# Salin data ke meja kerja
shutil.copytree(base_source, working_dir)
print(f"Data berhasil disalin ke: {working_dir}")

"""## 1.2 Raw Data Assessment
Sebelum melakukan pembersihan, kita akan melakukan audit terhadap dataset mentah untuk memahami keberagaman format warna, resolusi, dan ukuran file asli. Hal ini penting untuk memetakan tantangan teknis dalam tahap preprocessing.
"""

def extract_metadata(target_dir):
    data_list = []
    # Mengambil daftar kategori
    categories = [c for c in os.listdir(target_dir) if os.path.isdir(os.path.join(target_dir, c))]

    for cat in categories:
        cat_path = os.path.join(target_dir, cat)
        for file in os.listdir(cat_path):
            file_path = os.path.join(cat_path, file)
            try:
                with Image.open(file_path) as img:
                    data_list.append({
                        'Nama_File': file,
                        'Kategori': cat,
                        'Format_Warna': img.mode,
                        'Lebar': img.size[0],
                        'Tinggi': img.size[1],
                        'Ukuran_KB': round(os.path.getsize(file_path) / 1024, 2)
                    })
            except:
                pass
    return pd.DataFrame(data_list)

# Mengekstrak metadata dari data mentah
df_raw = extract_metadata(working_dir)

print("--- RAW DATA: df.head() ---")
display(df_raw.head())

print("\n--- RAW DATA: df.info() ---")
df_raw.info()

# Visual Inspection (Menampilkan dimensi asli yang acak)
print("\n--- RAW DATA: Visual Inspection ---")
categories = [c for c in os.listdir(working_dir) if os.path.isdir(os.path.join(working_dir, c))]
sample_count = 5

fig, axes = plt.subplots(len(categories), sample_count, figsize=(15, 3 * len(categories)))
for i, cat in enumerate(categories):
    cat_path = os.path.join(working_dir, cat)
    sample_files = os.listdir(cat_path)[:sample_count]
    for j, filename in enumerate(sample_files):
        img_path = os.path.join(cat_path, filename)
        try:
            img = mpimg.imread(img_path)
            ax = axes[i, j]
            ax.imshow(img)
            ax.axis('off')
            if j == 0:
                ax.set_title(f"Kategori: {cat.upper()}\nDimensi: {img.shape}", fontweight='bold', fontsize=10)
            else:
                ax.set_title(f"Dimensi: {img.shape}", fontsize=9)
        except Exception:
            axes[i, j].set_title("File Rusak", color='red', fontsize=9)
            axes[i, j].axis('off')

plt.tight_layout()
plt.show()

"""### 1.3 Data Cleaning & Balancing (Undersampling)
Proses pembersihan mencakup penghapusan file korup, standarisasi resolusi menjadi 224x224 piksel, dan format warna RGB. Setelah bersih, dilakukan *undersampling* untuk menyamaratakan jumlah data antar kelas.
"""

categories = [c for c in os.listdir(working_dir) if os.path.isdir(os.path.join(working_dir, c))]
removed_files = 0
updated_files = 0

# Pembersihan File Rusak & Standarisasi Visual
for cat in categories:
    cat_path = os.path.join(working_dir, cat)
    for file in os.listdir(cat_path):
        f_path = os.path.join(cat_path, file)
        try:
            with Image.open(f_path) as img:
                img.verify()

            with Image.open(f_path) as img:
                clean_img = img.convert('RGB').resize((224, 224))
                clean_img.save(f_path)
            updated_files += 1
        except Exception:
            os.remove(f_path)
            removed_files += 1

print(f"Hasil Cleaning: {updated_files} gambar distandarisasi, {removed_files} file rusak dihapus.\n")

# Penyeimbangan Data (Undersampling)
distribution = {c: len(os.listdir(os.path.join(working_dir, c))) for c in categories}
min_samples = min(distribution.values())

print(f"Distribusi awal: {distribution}")
print(f"Menyeimbangkan data ke: {min_samples} sampel per kelas.")

for cat in categories:
    target_path = os.path.join(working_dir, cat)
    all_imgs = os.listdir(target_path)
    if len(all_imgs) > min_samples:
        to_delete = random.sample(all_imgs, len(all_imgs) - min_samples)
        for f in to_delete:
            os.remove(os.path.join(target_path, f))

print("Data balancing berhasil diselesaikan.")

# Visualisasi Konfirmasi Hasil Balancing
final_counts = [len(os.listdir(os.path.join(working_dir, c))) for c in categories]

plt.figure(figsize=(8, 5))
bars = plt.bar(categories, final_counts, color=['#2ca02c', '#1f77b4', '#d62728'], alpha=0.8)
plt.title('Distribusi Kategori Dataset Setelah Balancing (Undersampling)', fontweight='bold')
plt.ylabel('Jumlah Sampel')

# Menambahkan angka pasti di atas bar
for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval + 20, int(yval), ha='center', va='bottom', fontweight='bold')

plt.ylim(0, max(final_counts) + 500)
plt.show()

"""## 2. Exploratory Data Analysis (EDA)
Setelah data bersih dan seimbang, kita kembali mengekstrak metadatanya untuk menganalisis dan memvisualisasikan karakteristik akhirnya, seperti ukuran file rata-rata, guna memastikan tidak ada anomali tersisa.
"""

# Ekstrak metadata ulang dari data yang sudah bersih
df_clean = extract_metadata(working_dir)

#DATA GROUPING & STATS PARAMETER
tabel_statistik = df_clean.groupby('Kategori')['Ukuran_KB'].agg(['mean', 'median', 'min', 'max']).reset_index()
tabel_statistik.rename(columns={'mean': 'Rata-rata (KB)', 'median': 'Nilai Tengah (KB)'}, inplace=True)
display(tabel_statistik)

# UNIVARIATE VISUALIZATION (Histogram)
plt.figure(figsize=(8, 5))
sns.histplot(data=df_clean, x='Ukuran_KB', hue='Kategori', kde=True, bins=30, alpha=0.6)
plt.title('Distribusi Ukuran File Gambar Setelah Standardisasi')
plt.xlabel('Ukuran File (KB)')
plt.ylabel('Frekuensi')
plt.show()

"""## 3. Visualization & Explanatory Analysis
Pada tahap ini, kita akan menjawab pertanyaan bisnis utama dengan memvisualisasikan temuan-temuan kunci yang telah ditemukan pada tahap EDA. Fokus kita adalah memberikan penjelasan yang mendalam (*explanatory*) di balik setiap grafik yang dihasilkan.

### **Pertanyaan 1**: Sejauh mana tingkat ketidakseimbangan kelas pada dataset mentah, dan bagaimana kita memastikan komposisi data seimbang agar model AI terhindar dari bias?
"""

# Menghitung distribusi akhir per kelas
final_counts = [len(os.listdir(os.path.join(working_dir, c))) for c in categories]

plt.figure(figsize=(8, 5))
bars = plt.bar(categories, final_counts, color=['#2ca02c', '#1f77b4', '#d62728'], alpha=0.8)
plt.title('Distribusi Kategori Dataset Trashify Setelah Balancing', fontweight='bold', fontsize=12)
plt.xlabel('Kategori Sampah', fontsize=10)
plt.ylabel('Jumlah Sampel Citra', fontsize=10)

for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval + 20, f"{int(yval)}", ha='center', va='bottom', fontweight='bold')

plt.ylim(0, max(final_counts) + 500)
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.show()

"""**Analisis Jawaban Pertanyaan 1:**\
Berdasarkan hasil ekstraksi awal pada dataset mentah, teridentifikasi adanya ketidakseimbangan kelas dengan distribusi: kelas Anorganik (3580 sampel) dan Organik (3507 sampel) mendominasi dibandingkan kelas Residu (3194 sampel). Jika dibiarkan, ketimpangan ini berisiko membuat model AI lebih pintar mengenali kelas mayoritas dan lemah pada kelas minoritas.

Untuk memastikan komposisi data yang seimbang dan bebas bias, diterapkan teknik Undersampling yang memangkas kelas mayoritas agar setara dengan batas kelas minoritas. Sebagaimana divalidasi oleh diagram batang di atas, intervensi algoritma ini telah berhasil menyamaratakan volume data secara mutlak menjadi ekuivalen sebesar 3194 sampel citra per kategori (rasio 1:1:1). Struktur data akhir yang simetris ini memastikan fungsi kerugian (loss function) pada arsitektur CNN memberikan pembobotan yang adil (unbiased) selama fase pelatihan.

### **Pertanyaan 2**: Bagaimana distribusi ukuran resolusi dan format warna pada dataset mentah, dan apakah langkah standarisasi visual diperlukan sebelum data diekspor?
"""

plt.figure(figsize=(9, 5))
sns.histplot(data=df_clean, x='Ukuran_KB', hue='Kategori', kde=True, bins=30, alpha=0.5)
plt.title('Analisis Kepadatan Ragam Ukuran File Gambar Setelah Standarisasi', fontweight='bold', fontsize=12)
plt.xlabel('Ukuran File (KB)', fontsize=10)
plt.ylabel('Frekuensi Kemunculan', fontsize=10)
plt.grid(True, linestyle='--', alpha=0.3)
plt.show()

"""**Analisis Jawaban Pertanyaan 2:**\
Berdasarkan tinjauan metadata di awal, dataset mentah memiliki distribusi ukuran resolusi yang sangat acak serta format warna yang tidak seragam. Hal ini mengonfirmasi bahwa langkah standarisasi visual sangat diperlukan sebelum data diekspor.

Sebagai bukti keberhasilan tindakan tersebut, kurva kepadatan dan histogram di atas menampilkan kondisi data pasca-standarisasi. Dapat dilihat bahwa pola distribusi ukuran file (KB) kini saling berhimpit secara konsisten di antara ketiga kelas sampah. Sebagian besar berkas telah terkonsentrasi secara seragam pada rentang ukuran tertentu. Fenomena ini memvalidasi bahwa tahapan pembatasan matriks gambar (resolusi 224x224) dan penyeragaman format saluran warna (RGB) telah berhasil mengeliminasi variansi ekstrem karakteristik visual data mentah dari dunia nyata.

### **Pertanyaan 3**: Berapa banyak file citra dalam dataset mentah yang terindikasi rusak (*corrupt*) atau memiliki format warna tidak standar, yang harus dibersihkan?
"""

# Menampilkan parameter kuantitatif kualitas data mentah
print(f"Jumlah file terindikasi rusak (Corrupt) : {removed_files} berkas")
print(f"Persentase kerusakan data mentah        : {round((removed_files / (updated_files + removed_files)) * 100, 3)}%")

"""**Analisis Jawaban Pertanyaan 3:**\
Berdasarkan kalkulasi log pembersihan data pada Tahap 1.2, teridentifikasi sebanyak **0 file citra** yang rusak (*corrupt*) atau mengalami kegagalan pembacaan struktur enkripsi oleh komponen *library* PIL. Jika terdapat file yang rusak, maka file tersebut akan dideklarasikan sebagai anomali dan akan dieliminasi secara permanen dari *working directory*. Langkah ini penting dilakukan agar tidak terjadi kesalahan pada tahap selanjutnya.

## 4. Data Splitting & Export
Pada tahap terakhir ini, kita membagi dataset yang sudah siap ini menjadi himpunan pelatihan, validasi, dan pengujian.
"""

final_export_dir = "/content/Trashify_Final_Dataset"
if os.path.exists(final_export_dir):
    shutil.rmtree(final_export_dir)

# Pembagian data dengan rasio 70:15:15
splitfolders.ratio(
    working_dir,
    output=final_export_dir,
    seed=1337,
    ratio=(0.7, 0.15, 0.15)
)

# Kompresi folder menjadi ZIP
!zip -r -q /content/Trashify_Dataset_Final.zip {final_export_dir}
print("Dataset telah dibersihkan, diseimbangkan, dipisah, dan siap digunakan.")

"""## Feature Engineering
Augmentasi dapat dilakukan di tahap balancing sebagai pengganti undersampling.
"""

# Penyeimbangan Data (Oversampling dengan Augmentasi)
distribution_awal = {c: len(os.listdir(os.path.join(working_dir, c))) for c in categories}
print(f"Distribusi awal pasca-cleaning: {distribution_awal}")

# PENGATURAN TARGET DATA
target_total_data = 23000
# Membagi rata target total ke semua kelas, dibulatkan ke atas
target_per_kelas = math.ceil(target_total_data / len(categories))

print(f"Target Oversampling: {target_per_kelas} sampel per kategori (Total ~{target_total_data} data).")

for cat in categories:
    target_path = os.path.join(working_dir, cat)
    files = os.listdir(target_path)
    deficit = target_per_kelas - len(files)

    if deficit > 0:
        for i in range(deficit):
            # Memilih gambar asli secara acak untuk dijadikan basis augmentasi
            source_file = random.choice(files)
            img_path = os.path.join(target_path, source_file)
            try:
                with Image.open(img_path) as img:
                    # Teknik Augmentasi 1: Mirroring (Peluang 50%)
                    if random.choice([True, False]):
                        img = ImageOps.mirror(img)

                    # Teknik Augmentasi 2: Rotasi Acak (-30 hingga 30 derajat)
                    img = img.rotate(random.randint(-30, 30))

                    # Menyimpan file sintetis baru
                    new_name = f"aug_{i}_{source_file}"
                    img.save(os.path.join(target_path, new_name))
            except Exception:
                pass

print("Prosedur data balancing (Oversampling Ekspansif) berhasil diselesaikan.")

print("Data balancing berhasil diselesaikan.")